window.PRODUCTS = [
  {
    id: 1,
    name: "Nike Air Jordan 1 Retro High OG NRG Igloo",
    category: "Sneakers",
    price: 200,
    size: "UK 7.5",
    condition: "8/10",
    description:
      "Classic black and igloo pair in good condition. Minor signs of wear consistent with preloved use.",
    image: [
      "assets/products/igloo-front.jpg",
      "assets/products/igloo-side.jpg",
      "assets/products/igloo-sole.jpg",
      "assets/products/igloo-tag.jpg",
    ],
    status: "AVAILABLE",
  },
  {
    id: 2,
    name: "SVG Victory Embroidery Leather Tee Black",
    category: "Tees",
    price: 250,
    size: "L",
    condition: "9/10",
    description:
      "Graphic tee with a clean streetwear silhouette. Preloved and inspected before listing.",
    image: ["assets/products/svg-front.jpg", "assets/products/svg-back.jpg"],
    status: "AVAILABLE",
  },
  {
    id: 3,
    name: "Homebois S13 Away Jersey",
    category: "Jerseys",
    price: 90,
    size: "M",
    condition: "9/10",
    description:
      "Homebois S13 Away Jersey. Comes with Udil nameset. Clean overall condition.",
    image: [
      "assets/products/homebois-dustbag.jpg",
      "assets/products/homebois-front.jpg",
      "assets/products/homebois-back.jpg",
    ],
    status: "SOLD",
  },
  {
    id: 4,
    name: "Shell V-Power Racing Team Polo Shirt",
    category: "Jerseys",
    price: 70,
    size: "2XL",
    condition: "9/10",
    description: "Shell red shirt in good condition.",
    image: [
      "assets/products/shell-full.jpg",
      "assets/products/shell-front.jpg",
      "assets/products/shell-back.jpg",
    ],
    status: "AVAILABLE",
  },
  {
    id: 5,
    name: "Nike FAM Light Blue Polo Shirt",
    category: "Tees",
    price: 40,
    size: "M",
    condition: "9/10",
    description: "FAM light blue polo shirt in good condition.",
    image: ["assets/products/fam-front.jpg", "assets/products/fam-back.jpg"],
    status: "AVAILABLE",
  },
  {
    id: 6,
    name: "Navy Blue Mizuno Dry-Fit Athletic Shirt",
    category: "Jerseys",
    price: 30,
    size: "M",
    condition: "9/10",
    description: "Navy blue dry-fit athletic shirt in good condition.",
    image: [
      "assets/products/mizuno-front.jpg",
      "assets/products/mizuno-back.jpg",
    ],
    status: "AVAILABLE",
  },
];
